name: Run Tests and Deploy

on:
  push:
    branches:
      - main
      - github-auto-deploy

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify installed packages
        run: |
            command -v python
            python --version
            pip list

      - name: Run Pytest
        run: python -m pytest tests/

      - name: Deploy to EC2
        if: success()
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: "/home/ec2-user/source/firma_web"
