name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: pytest tests/

      - name: Create SSH key file
        run: |
          echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Build Docker image
        run: docker build -t firma_app .

      - name: Save Docker image as tarball
        run: docker save firma_app > firma_app.tar

      - name: Copy image tarball to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ec2_key.pem firma_app.tar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/firma_app.tar

      - name: Deploy on EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker load < firma_app.tar
            docker stop firma_app || true
            docker rm firma_app || true
            docker run -d --name firma_app -p 80:80 \
              -e SECRET_KEY="${SECRET_KEY}" \
              firma_app
          EOF
